trigger: none

pr:
  branches:
    include:
    - main

variables:
  solution: '**/*.sln'
  configuration: 'Debug'

stages:
- stage: Build
  displayName: 'PR Validation'

  jobs:
  - job: BuildTestWindows
    displayName: 'Build and Test on Windows'
    pool:
      vmImage: 'windows-latest'
    workspace:
      clean: all
    steps:
    - template: 'template-steps-build-test-unix.yml'
      parameters:
        solution: '$(solution)'
        configuration: '$(configuration)'
        nugetVersion: '1.0.0-test'

- job: BuildTest
    displayName: 'Build and Test on'

    # Verifies cross-platform build and test
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macos-latest'

    pool:
      vmImage: '$(imageName)'

    workspace:
      clean: all

    steps:
    - template: 'template-steps-build-test-unix.yml'
      parameters:
        solution: '$(solution)'
        configuration: '$(configuration)'
        nugetVersion: '1.0.0-test'